package com.skybook.praveen.notificationservice.service;

import java.util.Map;

/**
 * Static IATA airport code -> city name lookup for the email template's
 * route card. flight-service treats origin/destination as free-text 3-char
 * codes (no airport reference table anywhere in the system), so this is a
 * best-effort map of common airports; unknown codes just render without a
 * city line.
 */
final class AirportCityLookup {

    private static final Map<String, String> CITY_BY_CODE = Map.ofEntries(
            Map.entry("LHR", "London"),
            Map.entry("LGW", "London"),
            Map.entry("LCY", "London"),
            Map.entry("STN", "London"),
            Map.entry("JFK", "New York"),
            Map.entry("EWR", "New York"),
            Map.entry("LGA", "New York"),
            Map.entry("LAX", "Los Angeles"),
            Map.entry("SFO", "San Francisco"),
            Map.entry("ORD", "Chicago"),
            Map.entry("MIA", "Miami"),
            Map.entry("SEA", "Seattle"),
            Map.entry("BOS", "Boston"),
            Map.entry("IAD", "Washington, D.C."),
            Map.entry("DFW", "Dallas"),
            Map.entry("ATL", "Atlanta"),
            Map.entry("YYZ", "Toronto"),
            Map.entry("YVR", "Vancouver"),
            Map.entry("CDG", "Paris"),
            Map.entry("ORY", "Paris"),
            Map.entry("FRA", "Frankfurt"),
            Map.entry("MUC", "Munich"),
            Map.entry("AMS", "Amsterdam"),
            Map.entry("MAD", "Madrid"),
            Map.entry("BCN", "Barcelona"),
            Map.entry("FCO", "Rome"),
            Map.entry("MXP", "Milan"),
            Map.entry("ZRH", "Zurich"),
            Map.entry("VIE", "Vienna"),
            Map.entry("CPH", "Copenhagen"),
            Map.entry("OSL", "Oslo"),
            Map.entry("ARN", "Stockholm"),
            Map.entry("DUB", "Dublin"),
            Map.entry("LIS", "Lisbon"),
            Map.entry("IST", "Istanbul"),
            Map.entry("SVO", "Moscow"),
            Map.entry("DXB", "Dubai"),
            Map.entry("AUH", "Abu Dhabi"),
            Map.entry("DOH", "Doha"),
            Map.entry("RUH", "Riyadh"),
            Map.entry("JED", "Jeddah"),
            Map.entry("DEL", "New Delhi"),
            Map.entry("BOM", "Mumbai"),
            Map.entry("BLR", "Bengaluru"),
            Map.entry("MAA", "Chennai"),
            Map.entry("HYD", "Hyderabad"),
            Map.entry("LTN", "London Luton"),
            Map.entry("SEN", "London Southend"),
            Map.entry("MAN", "Manchester"),
            Map.entry("LPL", "Liverpool"),
            Map.entry("BHX", "Birmingham"),
            Map.entry("EMA", "East Midlands"),
            Map.entry("NWI", "Norwich"),
            Map.entry("LBA", "Leeds Bradford"),
            Map.entry("NCL", "Newcastle"),
            Map.entry("MME", "Teesside"),
            Map.entry("BOH", "Bournemouth"),
            Map.entry("SOU", "Southampton"),
            Map.entry("EXT", "Exeter"),
            Map.entry("BRS", "Bristol"),
            Map.entry("CWL", "Cardiff"),
            Map.entry("NQY", "Newquay"),
            Map.entry("LEQ", "Land's End"),
            Map.entry("ISC", "Isles of Scilly"),
            Map.entry("EDI", "Edinburgh"),
            Map.entry("GLA", "Glasgow"),
            Map.entry("ABZ", "Aberdeen"),
            Map.entry("INV", "Inverness"),
            Map.entry("DND", "Dundee"),
            Map.entry("KOI", "Kirkwall"),
            Map.entry("LSI", "Shetland"),
            Map.entry("SYY", "Stornoway"),
            Map.entry("BEB", "Benbecula"),
            Map.entry("BRR", "Barra"),
            Map.entry("TRE", "Tiree"),
            Map.entry("ILY", "Islay"),
            Map.entry("CAL", "Campbeltown"),
            Map.entry("PPW", "Papa Westray"),
            Map.entry("NRL", "North Ronaldsay"),
            Map.entry("NDY", "Sanday"),
            Map.entry("WRY", "Westray"),
            Map.entry("SOY", "Stronsay"),
            Map.entry("BFS", "Belfast Intl"),
            Map.entry("BHD", "Belfast City"),
            Map.entry("LDY", "Derry"),
            Map.entry("JER", "Jersey"),
            Map.entry("GCI", "Guernsey"),
            Map.entry("ACI", "Alderney"),
            Map.entry("IOM", "Isle of Man"),
            Map.entry("AMD", "Ahmedabad"),
            Map.entry("PNQ", "Pune"),
            Map.entry("GOI", "Goa Dabolim"),
            Map.entry("GOX", "Goa Mopa"),
            Map.entry("COK", "Kochi"),
            Map.entry("TRV", "Thiruvananthapuram"),
            Map.entry("NAG", "Nagpur"),
            Map.entry("JAI", "Jaipur"),
            Map.entry("LKO", "Lucknow"),
            Map.entry("IXC", "Chandigarh"),
            Map.entry("ATQ", "Amritsar"),
            Map.entry("GAU", "Guwahati"),
            Map.entry("BBI", "Bhubaneswar"),
            Map.entry("PAT", "Patna"),
            Map.entry("IDR", "Indore"),
            Map.entry("BHO", "Bhopal"),
            Map.entry("RPR", "Raipur"),
            Map.entry("VNS", "Varanasi"),
            Map.entry("SXR", "Srinagar"),
            Map.entry("IXB", "Siliguri"),
            Map.entry("CJB", "Coimbatore"),
            Map.entry("CCJ", "Kozhikode"),
            Map.entry("IXE", "Mangaluru"),
            Map.entry("IXZ", "Port Blair"),
            Map.entry("IXR", "Ranchi"),
            Map.entry("DED", "Dehradun"),
            Map.entry("UDR", "Udaipur"),
            Map.entry("JDH", "Jodhpur"),
            Map.entry("STV", "Surat"),
            Map.entry("CNN", "Kannur"),
            Map.entry("IXM", "Madurai"),
            Map.entry("TRZ", "Tiruchirappalli"),
            Map.entry("TIR", "Tirupati"),
            Map.entry("VGA", "Vijayawada"),
            Map.entry("RJA", "Rajahmundry"),
            Map.entry("IXU", "Aurangabad"),
            Map.entry("JLR", "Jabalpur"),
            Map.entry("JRG", "Jharsuguda"),
            Map.entry("GAY", "Gaya"),
            Map.entry("IXD", "Prayagraj"),
            Map.entry("GWL", "Gwalior"),
            Map.entry("JGA", "Jamnagar"),
            Map.entry("RAJ", "Rajkot"),
            Map.entry("HSR", "Rajkot"),
            Map.entry("BHJ", "Bhuj"),
            Map.entry("BDQ", "Vadodara"),
            Map.entry("KNU", "Kanpur"),
            Map.entry("GOP", "Gorakhpur"),
            Map.entry("DBR", "Darbhanga"),
            Map.entry("IXJ", "Jammu"),
            Map.entry("IXL", "Leh"),
            Map.entry("DHM", "Dharamshala"),
            Map.entry("KUU", "Kullu"),
            Map.entry("IMF", "Imphal"),
            Map.entry("DIB", "Dibrugarh"),
            Map.entry("JRH", "Jorhat"),
            Map.entry("SHL", "Shillong"),
            Map.entry("AJL", "Aizawl"),
            Map.entry("DMU", "Dimapur"),
            Map.entry("IXA", "Agartala"),
            Map.entry("IXS", "Silchar"),
            Map.entry("HBX", "Hubballi"),
            Map.entry("MYQ", "Mysuru"),
            Map.entry("PGH", "Pantnagar"),
            Map.entry("TEZ", "Tezpur"),
            Map.entry("VTZ", "Visakhapatnam"),
            Map.entry("CCU", "Kolkata"),
            Map.entry("PEK", "Beijing"),
            Map.entry("PVG", "Shanghai"),
            Map.entry("HKG", "Hong Kong"),
            Map.entry("NRT", "Tokyo"),
            Map.entry("HND", "Tokyo"),
            Map.entry("ICN", "Seoul"),
            Map.entry("SIN", "Singapore"),
            Map.entry("KUL", "Kuala Lumpur"),
            Map.entry("BKK", "Bangkok"),
            Map.entry("CGK", "Jakarta"),
            Map.entry("MNL", "Manila"),
            Map.entry("SYD", "Sydney"),
            Map.entry("MEL", "Melbourne"),
            Map.entry("AKL", "Auckland"),
            Map.entry("JNB", "Johannesburg"),
            Map.entry("CPT", "Cape Town"),
            Map.entry("CAI", "Cairo"),
            Map.entry("LOS", "Lagos"),
            Map.entry("NBO", "Nairobi"),
            Map.entry("GRU", "São Paulo"),
            Map.entry("GIG", "Rio de Janeiro"),
            Map.entry("EZE", "Buenos Aires"),
            Map.entry("MEX", "Mexico City"),
            Map.entry("YUL", "Montreal")
    );

    private AirportCityLookup() {
    }

    /** City name for an IATA code, or null if the code isn't in the lookup. */
    static String cityFor(String iataCode) {
        return iataCode == null ? null : CITY_BY_CODE.get(iataCode.toUpperCase());
    }
}
