-- ROUND_TRIP_MODULE.md §3/§8: multi-segment bookings (single-PNR round trips).
--
-- booking_segments: one row per flight leg of the journey (segment_index 0 =
-- outbound, 1 = return). No route snapshot - flights rows are already dated
-- instances and events enrich at publish time, exactly as bookings.flight_id
-- works today.
--
-- Every existing booking becomes a valid single-segment booking: backfill one
-- segment 0 per booking from bookings.flight_id, then point every passenger
-- row at it. bookings.flight_id itself is KEPT for one release (deprecated,
-- documented as segment 0's flight) - dropped by a follow-up migration once
-- all readers are on segments.

CREATE TABLE booking_segments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    booking_id bigint NOT NULL REFERENCES bookings(id),
    segment_index int NOT NULL,
    flight_id bigint NOT NULL,
    CONSTRAINT uk_booking_segment_index UNIQUE (booking_id, segment_index)
);

INSERT INTO booking_segments (created_at, created_by, updated_at, version, booking_id, segment_index, flight_id)
SELECT now(), 'migration-v10', now(), 0, id, 0, flight_id
FROM bookings;

ALTER TABLE booking_passengers ADD COLUMN segment_id bigint REFERENCES booking_segments(id);

UPDATE booking_passengers bp
SET segment_id = s.id
FROM booking_segments s
WHERE s.booking_id = bp.booking_id AND s.segment_index = 0;

ALTER TABLE booking_passengers ALTER COLUMN segment_id SET NOT NULL;

CREATE INDEX idx_booking_segments_booking ON booking_segments(booking_id);
CREATE INDEX idx_booking_passengers_segment ON booking_passengers(segment_id);
