-- ROUND_TRIP_MODULE.md, tickets & coupons: IATA-style ticketing.
-- One ticket per (booking x traveller) covering the whole journey; one
-- coupon per segment, 1:1 with the traveller's per-segment
-- booking_passengers row. Issued when a booking reaches CONFIRMED.
--
-- No backfill: tickets exist for bookings confirmed AFTER this release.
-- Historical bookings keep rendering their e-ticket from booking data alone.

CREATE TABLE tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    booking_id bigint NOT NULL REFERENCES bookings(id),
    passenger_id bigint NOT NULL REFERENCES passengers(id),
    ticket_number varchar(16) NOT NULL UNIQUE,
    status varchar(10) NOT NULL,
    issued_at timestamp(6) NOT NULL
);

CREATE TABLE ticket_coupons (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    ticket_id bigint NOT NULL REFERENCES tickets(id),
    booking_passenger_id bigint NOT NULL UNIQUE REFERENCES booking_passengers(id),
    coupon_number int NOT NULL,
    status varchar(12) NOT NULL
);

CREATE INDEX idx_tickets_booking ON tickets(booking_id);
CREATE INDEX idx_ticket_coupons_ticket ON ticket_coupons(ticket_id);
