-- Fare watch (passenger features): a signed-in user watches a route + date +
-- cabin; a scheduled job reprices it with the SAME deterministic
-- FareCalculator checkout uses and emails when the fare moves. With
-- demand-shaped pricing fares rise toward departure, so in practice these
-- are honest "book before it goes up" warnings.
CREATE TABLE fare_alerts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    owner_subject varchar(255) NOT NULL,
    origin_airport_code varchar(3) NOT NULL,
    destination_airport_code varchar(3) NOT NULL,
    travel_date date NOT NULL,
    travel_class varchar(20) NOT NULL,
    last_notified_fare numeric(19,2),
    active boolean NOT NULL DEFAULT true
);

CREATE INDEX idx_fare_alerts_owner ON fare_alerts(owner_subject);
CREATE INDEX idx_fare_alerts_active ON fare_alerts(active) WHERE active;
