-- Baseline: booking-service's schema exactly as Hibernate ddl-auto created it
-- BEFORE the seat-selection branch (dumped from a live pre-branch database).
--
-- Runs ONLY on a genuinely fresh database (SEAT_SELECTION_MODULE.md §8):
-- existing Hibernate-created databases are adopted at this version via
-- baseline-on-migrate + baseline-version: 1, so Flyway skips this file there
-- and applies only V2+. Both paths converge on the same schema, verified by
-- ddl-auto: validate at startup.

CREATE TABLE booking_contacts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    contact_email varchar(255) NOT NULL,
    contact_name varchar(255) NOT NULL,
    contact_phone varchar(255),
    booking_id bigint NOT NULL
);

CREATE TABLE booking_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    changed_at timestamp(6) NOT NULL,
    changed_by varchar(255),
    field_changed varchar(20) NOT NULL,
    from_value varchar(255) NOT NULL,
    reason varchar(255),
    to_value varchar(255) NOT NULL,
    booking_id bigint NOT NULL,
    CONSTRAINT booking_history_field_changed_check
        CHECK (field_changed IN ('BOOKING_STATUS', 'PAYMENT_STATUS', 'CHECK_IN_STATUS'))
);

CREATE TABLE passengers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    dob date NOT NULL,
    email varchar(255),
    first_name varchar(255) NOT NULL,
    gender varchar(20),
    last_name varchar(255) NOT NULL,
    middle_name varchar(255),
    nationality varchar(3) NOT NULL,
    passport_expiry date NOT NULL,
    passport_number varchar(20) NOT NULL,
    phone varchar(255),
    title varchar(10)
);

CREATE TABLE bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    booking_date timestamp(6) NOT NULL,
    booking_reference varchar(10) NOT NULL,
    booking_status varchar(20) NOT NULL,
    customer_id bigint NOT NULL,
    flight_id bigint NOT NULL,
    remarks varchar(500),
    total_fare numeric(38,2) NOT NULL,
    CONSTRAINT bookings_booking_status_check
        CHECK (booking_status IN ('CREATED', 'CONFIRMED', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT uke92mgyq35mdeo8gc1un2o6uk0 UNIQUE (booking_reference)
);

CREATE TABLE booking_passengers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    check_in_status varchar(20) NOT NULL,
    fare numeric(38,2) NOT NULL,
    fare_type varchar(20) NOT NULL,
    flight_id bigint NOT NULL,
    seat_number varchar(5) NOT NULL,
    travel_class varchar(20) NOT NULL,
    booking_id bigint NOT NULL,
    passenger_id bigint NOT NULL,
    CONSTRAINT booking_passengers_check_in_status_check
        CHECK (check_in_status IN ('NOT_OPEN', 'OPEN', 'CHECKED_IN', 'BOARDED', 'NO_SHOW', 'CLOSED')),
    CONSTRAINT booking_passengers_fare_type_check
        CHECK (fare_type IN ('SAVER', 'FLEXI', 'PREMIUM')),
    CONSTRAINT booking_passengers_travel_class_check
        CHECK (travel_class IN ('ECONOMY', 'PREMIUM_ECONOMY', 'BUSINESS', 'FIRST')),
    CONSTRAINT uk_flight_seat UNIQUE (flight_id, seat_number),
    CONSTRAINT fk6bkg00unp3sjkef5x2p0kwmit FOREIGN KEY (passenger_id) REFERENCES passengers (id),
    CONSTRAINT fkg23xsssayx3p1pqc9g8cbgm8p FOREIGN KEY (booking_id) REFERENCES bookings (id)
);

CREATE TABLE booking_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) NOT NULL,
    created_by varchar(100),
    updated_at timestamp(6) NOT NULL,
    updated_by varchar(100),
    version bigint,
    amount numeric(38,2) NOT NULL,
    currency varchar(3) NOT NULL,
    external_payment_reference varchar(255),
    paid_at timestamp(6),
    payment_status varchar(20) NOT NULL,
    booking_id bigint NOT NULL,
    CONSTRAINT booking_payments_payment_status_check
        CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
    CONSTRAINT ukgqdkqjcd7akvs0k2fum1kw1fk UNIQUE (booking_id),
    CONSTRAINT fkfhwt29c9x2ibo2o6r2ieq84ej FOREIGN KEY (booking_id) REFERENCES bookings (id)
);

ALTER TABLE booking_contacts
    ADD CONSTRAINT ukhx0cqucngyydk373nvis8i1vi UNIQUE (booking_id),
    ADD CONSTRAINT fkaa9s9xyf52266dih8qgirhx74 FOREIGN KEY (booking_id) REFERENCES bookings (id);

ALTER TABLE booking_history
    ADD CONSTRAINT fkn3ixdgggwbtcy80ja81sjvaqv FOREIGN KEY (booking_id) REFERENCES bookings (id);
