-- Baseline checkin schema (SECURITY_HARDENING_MODULE.md §4.5), dumped from the live DB.
-- Guarded: a no-op on the existing populated DB (tables already present),
-- a full create on a fresh one - so it is safe regardless of Flyway's
-- baseline-on-migrate emptiness detection (same robustness as auth V1).

DO $do$
BEGIN
    IF to_regclass('public.check_ins') IS NOT NULL THEN
        RAISE NOTICE 'checkin schema already present - baseline is a no-op';
        RETURN;
    END IF;

CREATE TABLE public.baggage (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    excess boolean NOT NULL,
    excess_charge numeric(38,2),
    tag_number character varying(20) NOT NULL,
    weight_kg numeric(38,2) NOT NULL,
    check_in_id bigint NOT NULL
);
ALTER TABLE public.baggage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.baggage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.boarding_passes (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    boarding_group character varying(5),
    boarding_pass_number character varying(20) NOT NULL,
    boarding_time timestamp(6) without time zone,
    booking_reference character varying(10) NOT NULL,
    destination_airport_code character varying(3),
    flight_number character varying(10),
    gate character varying(10),
    issued_at timestamp(6) without time zone NOT NULL,
    origin_airport_code character varying(3),
    passenger_name character varying(200) NOT NULL,
    reissued_as_id bigint,
    revoked_at timestamp(6) without time zone,
    seat_number character varying(5),
    status character varying(10) NOT NULL,
    token character varying(255) NOT NULL,
    check_in_id bigint NOT NULL,
    CONSTRAINT boarding_passes_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'REVOKED'::character varying])::text[])))
);
ALTER TABLE public.boarding_passes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.boarding_passes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.check_in_history (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    actor character varying(20) NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    correlation_id character varying(64),
    details character varying(500),
    history_type character varying(25) NOT NULL,
    source character varying(30) NOT NULL,
    check_in_id bigint NOT NULL,
    CONSTRAINT check_in_history_history_type_check CHECK (((history_type)::text = ANY ((ARRAY['CHECKIN_CREATED'::character varying, 'CHECKIN_OPENED'::character varying, 'CHECKED_IN'::character varying, 'BOARDED'::character varying, 'NO_SHOW'::character varying, 'CANCELLED'::character varying, 'SEAT_CHANGED'::character varying, 'BAGGAGE_ADDED'::character varying, 'BOARDING_PASS_ISSUED'::character varying, 'BOARDING_PASS_REVOKED'::character varying])::text[])))
);
ALTER TABLE public.check_in_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.check_in_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.check_ins (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    boarded_at timestamp(6) without time zone,
    boarding_group character varying(5),
    booking_id bigint NOT NULL,
    booking_passenger_id bigint NOT NULL,
    booking_reference character varying(10) NOT NULL,
    checked_in_at timestamp(6) without time zone,
    contact_email character varying(200),
    departure_time timestamp(6) without time zone,
    destination_airport_code character varying(3),
    document_verified boolean NOT NULL,
    fare_type character varying(20),
    flight_id bigint NOT NULL,
    flight_number character varying(10),
    gate character varying(10),
    origin_airport_code character varying(3),
    passenger_name character varying(200) NOT NULL,
    seat_number character varying(5),
    status character varying(15) NOT NULL,
    travel_class character varying(20),
    entitlement_currency character varying(3),
    seat_surcharge_entitlement numeric(19,2),
    CONSTRAINT check_ins_status_check CHECK (((status)::text = ANY ((ARRAY['NOT_OPEN'::character varying, 'OPEN'::character varying, 'CHECKED_IN'::character varying, 'BOARDED'::character varying, 'COMPLETED'::character varying, 'NO_SHOW'::character varying, 'CANCELLED'::character varying])::text[])))
);
ALTER TABLE public.check_ins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.check_ins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.flight_manifests (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    baggage_count integer,
    baggage_weight_kg numeric(38,2),
    boarded_count integer,
    checked_in_count integer,
    finalized_at timestamp(6) without time zone,
    flight_id bigint NOT NULL,
    no_show_count integer,
    status character varying(10) NOT NULL,
    CONSTRAINT flight_manifests_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'FINALIZED'::character varying])::text[])))
);
ALTER TABLE public.flight_manifests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.flight_manifests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.baggage
    ADD CONSTRAINT baggage_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.boarding_passes
    ADD CONSTRAINT boarding_passes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.check_in_history
    ADD CONSTRAINT check_in_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.check_ins
    ADD CONSTRAINT check_ins_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.flight_manifests
    ADD CONSTRAINT flight_manifests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.flight_manifests
    ADD CONSTRAINT uk8lijqywqadufxpm0picw804xt UNIQUE (flight_id);
ALTER TABLE ONLY public.check_ins
    ADD CONSTRAINT uk_checkin_booking_passenger UNIQUE (booking_passenger_id);
ALTER TABLE ONLY public.boarding_passes
    ADD CONSTRAINT ukpahyykq83qou3sdkywdoyykcl UNIQUE (token);
ALTER TABLE ONLY public.baggage
    ADD CONSTRAINT ukpnsqdj3knvbscxnfg38elk7ql UNIQUE (tag_number);
ALTER TABLE ONLY public.boarding_passes
    ADD CONSTRAINT uksnn5ilj1fkb0fiu4q8bj42ke UNIQUE (boarding_pass_number);
CREATE INDEX ix_baggage_checkin ON public.baggage USING btree (check_in_id);
CREATE INDEX ix_boarding_pass_checkin ON public.boarding_passes USING btree (check_in_id);
CREATE INDEX ix_check_in_history_checkin ON public.check_in_history USING btree (check_in_id);
ALTER TABLE ONLY public.boarding_passes
    ADD CONSTRAINT fkb0ny1n8knwe2m2kedjrdjmtye FOREIGN KEY (check_in_id) REFERENCES public.check_ins(id);
ALTER TABLE ONLY public.check_in_history
    ADD CONSTRAINT fkj1orbvn6irhdagol5vkhs7lm9 FOREIGN KEY (check_in_id) REFERENCES public.check_ins(id);
ALTER TABLE ONLY public.baggage
    ADD CONSTRAINT fknonxf75wagjonvn27g4t4h65d FOREIGN KEY (check_in_id) REFERENCES public.check_ins(id);

END
$do$;
