-- Baseline payment schema (SECURITY_HARDENING_MODULE.md §4.5), dumped from the live DB.
-- Guarded: a no-op on the existing populated DB (tables already present),
-- a full create on a fresh one - so it is safe regardless of Flyway's
-- baseline-on-migrate emptiness detection (same robustness as auth V1).

DO $do$
BEGIN
    IF to_regclass('public.payments') IS NOT NULL THEN
        RAISE NOTICE 'payment schema already present - baseline is a no-op';
        RETURN;
    END IF;

CREATE SEQUENCE public.invoice_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
CREATE TABLE public.invoices (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    booking_reference character varying(10) NOT NULL,
    currency character varying(3) NOT NULL,
    discount numeric(38,2) NOT NULL,
    grand_total numeric(38,2) NOT NULL,
    invoice_number character varying(20) NOT NULL,
    issued_at timestamp(6) without time zone NOT NULL,
    subtotal numeric(38,2) NOT NULL,
    tax_amount numeric(38,2) NOT NULL,
    payment_id bigint NOT NULL,
    base_fare_total numeric(19,2),
    seat_surcharge_total numeric(19,2)
);
ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.payment_history (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    actor character varying(20) NOT NULL,
    changed_at timestamp(6) without time zone NOT NULL,
    correlation_id character varying(64),
    details character varying(500),
    history_type character varying(25) NOT NULL,
    source character varying(30) NOT NULL,
    payment_id bigint NOT NULL,
    CONSTRAINT payment_history_history_type_check CHECK (((history_type)::text = ANY ((ARRAY['PAYMENT_CREATED'::character varying, 'AUTHORIZED'::character varying, 'AUTHORIZATION_FAILED'::character varying, 'CAPTURED'::character varying, 'CAPTURE_FAILED'::character varying, 'CANCELLED'::character varying, 'REFUND_REQUESTED'::character varying, 'REFUND_COMPLETED'::character varying, 'REFUND_FAILED'::character varying])::text[])))
);
ALTER TABLE public.payment_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.payment_transactions (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    amount numeric(38,2) NOT NULL,
    duration_ms bigint,
    gateway_message character varying(255),
    gateway_reference character varying(100),
    gateway_response_code character varying(30),
    occurred_at timestamp(6) without time zone NOT NULL,
    raw_gateway_payload text,
    status character varying(10) NOT NULL,
    transaction_reference character varying(20) NOT NULL,
    type character varying(15) NOT NULL,
    payment_id bigint NOT NULL,
    CONSTRAINT payment_transactions_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCEEDED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT payment_transactions_type_check CHECK (((type)::text = ANY ((ARRAY['AUTHORIZE'::character varying, 'CAPTURE'::character varying, 'VOID'::character varying, 'REFUND'::character varying])::text[])))
);
ALTER TABLE public.payment_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.payments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    amount numeric(38,2) NOT NULL,
    booking_id bigint NOT NULL,
    booking_reference character varying(10) NOT NULL,
    captured_amount numeric(38,2) NOT NULL,
    currency character varying(3) NOT NULL,
    failure_reason character varying(255),
    fare_breakdown character varying(1000),
    gateway_reference character varying(100),
    idempotency_key character varying(64),
    method character varying(15) NOT NULL,
    payment_reference character varying(20) NOT NULL,
    refunded_amount numeric(38,2) NOT NULL,
    status character varying(25) NOT NULL,
    base_fare_total numeric(19,2),
    seat_surcharge_total numeric(19,2),
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['CARD'::character varying, 'UPI'::character varying, 'BANK_TRANSFER'::character varying, 'APPLE_PAY'::character varying, 'GOOGLE_PAY'::character varying, 'PAYPAL'::character varying])::text[]))),
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'AUTHORIZATION_FAILED'::character varying, 'AUTHORIZED'::character varying, 'CAPTURE_FAILED'::character varying, 'CAPTURED'::character varying, 'PARTIALLY_REFUNDED'::character varying, 'REFUNDED'::character varying, 'CANCELLED'::character varying])::text[])))
);
ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE public.refunds (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    updated_at timestamp(6) without time zone NOT NULL,
    updated_by character varying(100),
    version bigint,
    amount numeric(38,2) NOT NULL,
    cancellation_fee numeric(38,2) NOT NULL,
    completed_at timestamp(6) without time zone,
    reason character varying(500),
    refund_reference character varying(20) NOT NULL,
    status character varying(15) NOT NULL,
    payment_id bigint NOT NULL,
    CONSTRAINT refunds_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);
ALTER TABLE public.refunds ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refunds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payment_history
    ADD CONSTRAINT payment_history_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT refunds_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT uk2irx02s3tuilqcgvcvemmd04l UNIQUE (refund_reference);
ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk4jacl30fsqtdp5mhmg5wnvn7q UNIQUE (payment_reference);
ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT uk61bc7vee8p067jyvyip7ja2yb UNIQUE (transaction_reference);
ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT uk8cfbd92rwby0aqvqocuv6aa05 UNIQUE (payment_id);
ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukj4pdqn1207fuhx2gybp1ue799 UNIQUE (idempotency_key);
ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT ukl1x55mfsay7co0r3m9ynvipd5 UNIQUE (invoice_number);
ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uknuscjm6x127hkb15kcb8n56wo UNIQUE (booking_id);
CREATE INDEX ix_payment_history_payment ON public.payment_history USING btree (payment_id);
CREATE INDEX ix_payment_transactions_payment ON public.payment_transactions USING btree (payment_id);
CREATE INDEX ix_refunds_payment ON public.refunds USING btree (payment_id);
ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT fkgu8q4u0cjr8aljtknj557g2i8 FOREIGN KEY (payment_id) REFERENCES public.payments(id);
ALTER TABLE ONLY public.refunds
    ADD CONSTRAINT fkpt9ic0j1y6xwlej99wnynvnpy FOREIGN KEY (payment_id) REFERENCES public.payments(id);
ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fkq6fs19k0gqw3rg0mb87h60h6p FOREIGN KEY (payment_id) REFERENCES public.payments(id);
ALTER TABLE ONLY public.payment_history
    ADD CONSTRAINT fksf1llvalsv3uwq221wvn49jc8 FOREIGN KEY (payment_id) REFERENCES public.payments(id);

END
$do$;
