-- India fleet (generated by gen_india_network.mjs): honest cabins per hull.
-- ATR 72 and every LCC narrow-body are ALL-ECONOMY - the whole point of the
-- exercise; only the AI A320neo carries a small Business cabin, sold on metro
-- trunks. Idempotent by registration. Run against skybook_inventory.

DO $$
DECLARE
  v_id bigint;
BEGIN

  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'VT-IGA') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-india', 0, 'VT-IGA', 'Airbus', 'A320neo (IndiGo)', 'ACTIVE', 180)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, r IN (12, 13), 'ACTIVE'
    FROM generate_series(1, 30) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'VT-IGB') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-india', 0, 'VT-IGB', 'Airbus', 'A321neo (IndiGo)', 'ACTIVE', 222)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, r IN (11, 24), 'ACTIVE'
    FROM generate_series(1, 37) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'VT-EXA') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-india', 0, 'VT-EXA', 'Airbus', 'A320neo (Air India)', 'ACTIVE', 164)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'BUSINESS', l.pos, r IN (-1), 'ACTIVE'
    FROM generate_series(1, 2) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, r IN (12, 13), 'ACTIVE'
    FROM generate_series(3, 28) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'VT-AXB') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-india', 0, 'VT-AXB', 'Boeing', '737-8 (AI Express)', 'ACTIVE', 186)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, r IN (14, 15), 'ACTIVE'
    FROM generate_series(1, 31) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'VT-QPB') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-india', 0, 'VT-QPB', 'Boeing', '737-8 (Akasa Air)', 'ACTIVE', 186)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, r IN (14, 15), 'ACTIVE'
    FROM generate_series(1, 31) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'VT-SGB') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-india', 0, 'VT-SGB', 'Boeing', '737-800 (SpiceJet)', 'ACTIVE', 186)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, r IN (14, 15), 'ACTIVE'
    FROM generate_series(1, 31) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'VT-ATA') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-india', 0, 'VT-ATA', 'ATR', '72-600', 'ACTIVE', 70)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, r IN (1, 12), 'ACTIVE'
    FROM generate_series(1, 17) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-india', 0, v_id, '18' || l.letter, 18, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM (VALUES ('A','WINDOW'),('C','AISLE')) AS l(letter, pos);
  END IF;
END $$;
