-- UK fleet (generated by gen_uk_network.mjs): honest cabins per hull.
-- BA's two-class Airbus and CityFlyer E190 are the ONLY UK domestic
-- Business (Club Europe); every LCC, regional, island and Crown carrier
-- hull is all-economy. Idempotent by registration. Run against
-- skybook_inventory.

DO $$
DECLARE
  v_id bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-SBBA') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-SBBA', 'Airbus', 'A320 (BA Club Europe)', 'ACTIVE', 162)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'BUSINESS', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 3) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(4, 28) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-SBBC') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-SBBC', 'Embraer', 'E190 (BA CityFlyer)', 'ACTIVE', 100)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'BUSINESS', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 3) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(4, 25) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-EZSB') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-EZSB', 'Airbus', 'A320 (easyJet)', 'ACTIVE', 180)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 30) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-EZSA') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-EZSA', 'Airbus', 'A319 (easyJet)', 'ACTIVE', 156)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 26) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-EAGS') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-EAGS', 'ATR', '72-600 (Emerald UK)', 'ACTIVE', 72)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 18) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-LMSA') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-LMSA', 'ATR', '72-600 (Loganair)', 'ACTIVE', 72)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 18) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-LMSB') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-LMSB', 'ATR', '42-500 (Loganair)', 'ACTIVE', 48)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 12) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-LMSC') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-LMSC', 'Embraer', 'ERJ145 (Loganair)', 'ACTIVE', 48)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 16) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-LMST') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-LMST', 'De Havilland', 'DHC-6 Twin Otter (Loganair)', 'ACTIVE', 20)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 5) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-LMSI') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-LMSI', 'Britten-Norman', 'BN-2 Islander (Loganair)', 'ACTIVE', 8)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 4) r,
         (VALUES ('A','WINDOW'),('C','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-RUKS') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-RUKS', 'Boeing', '737-800 (Ryanair UK)', 'ACTIVE', 192)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 32) r,
         (VALUES ('A','WINDOW'),('B','MIDDLE'),('C','AISLE'),('D','AISLE'),('E','MIDDLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-GRSA') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-GRSA', 'ATR', '72-600 (Aurigny)', 'ACTIVE', 72)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 18) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-GRSD') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-GRSD', 'Dornier', '228 (Aurigny)', 'ACTIVE', 20)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 5) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM aircraft WHERE registration_number = 'G-SBYT') THEN
    INSERT INTO aircraft (created_at, updated_at, created_by, version, registration_number, manufacturer, model, status, total_seats)
    VALUES (now(), now(), 'data-seed-uk', 0, 'G-SBYT', 'De Havilland', 'DHC-6 Twin Otter (Skybus)', 'ACTIVE', 20)
    RETURNING id INTO v_id;

    INSERT INTO aircraft_seats (created_at, updated_at, created_by, version, aircraft_id, seat_number, row_number, seat_type, position, exit_row, status)
    SELECT now(), now(), 'data-seed-uk', 0, v_id, r || l.letter, r, 'ECONOMY', l.pos, false, 'ACTIVE'
    FROM generate_series(1, 5) r,
         (VALUES ('A','WINDOW'),('C','AISLE'),('D','AISLE'),('F','WINDOW')) AS l(letter, pos);
  END IF;
END $$;
