-- Full pre-branch auth schema (SECURITY_HARDENING_MODULE.md §4.3). Idempotent
-- (IF NOT EXISTS) so it is a safe no-op on an existing Hibernate-created
-- database and a full create on a fresh one - the baseline converges either
-- way, without depending on Flyway's baseline-on-migrate emptiness detection.
-- Mirrors the live users table.

CREATE TABLE IF NOT EXISTS users (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     varchar(255) NOT NULL,
    full_name varchar(255),
    password  varchar(255),
    CONSTRAINT uk_users_email UNIQUE (email)
);
