-- Passenger profile (FRONTEND_MODULE.md Module 14). Extends the user with the
-- personal, passport and emergency-contact details a traveller would keep on
-- file, plus a separate table of saved travellers they can reuse at booking
-- time. All profile columns are nullable - an existing account has none of this
-- until the passenger fills it in.

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS phone                    varchar(30),
    ADD COLUMN IF NOT EXISTS date_of_birth            date,
    ADD COLUMN IF NOT EXISTS nationality              varchar(3),
    ADD COLUMN IF NOT EXISTS passport_number          varchar(30),
    ADD COLUMN IF NOT EXISTS passport_expiry          date,
    ADD COLUMN IF NOT EXISTS emergency_contact_name   varchar(255),
    ADD COLUMN IF NOT EXISTS emergency_contact_phone  varchar(30);

-- Saved travellers: reusable companion profiles owned by a user, so a booking
-- for family/colleagues doesn't retype passport details every time.
CREATE TABLE IF NOT EXISTS saved_travellers (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          bigint       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title            varchar(10),
    first_name       varchar(255) NOT NULL,
    last_name        varchar(255) NOT NULL,
    date_of_birth    date,
    nationality      varchar(3),
    passport_number  varchar(30),
    passport_expiry  date,
    created_at       timestamp    NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_saved_travellers_user_id ON saved_travellers (user_id);
